spring:
  config:
    activate:
      on-profile: staging
  datasource:
    url: ${STAGING_DATABASE_URL}
    username: ${STAGING_DATABASE_USER}
    password: ${STAGING_DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 15
  data:
    redis:
      host: ${STAGING_REDIS_HOST}
      port: 6379

management:
  endpoint:
    health:
      show-details: when_authorized

lms:
  course-service:
    url: ${STAGING_COURSE_SERVICE_URL:http://lms-course-service-staging:8080}
