apiVersion: v1
kind: Service
metadata:
  name: lms-assignment-service
  namespace: lms
spec:
  ports:
  - port: 8087
    targetPort: 8087
  selector:
    app: lms-assignment-service
    version: blue
