apiVersion: v1
kind: Service
metadata:
  name: lms-enrollment-service
  namespace: lms
spec:
  ports:
  - port: 8084
    targetPort: 8084
  selector:
    app: lms-enrollment-service
    version: blue
