apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-gateway-blue
  namespace: lms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lms-gateway
      version: blue
  template:
    metadata:
      labels:
        app: lms-gateway
        version: blue
    spec:
      containers:
      - name: lms-gateway
        image: lms-gateway:latest
        ports:
        - containerPort: 8080
        env:
        - name: DEPLOY_COLOR
          value: "blue"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: lms-secrets
              key: JWT_SECRET
        envFrom:
        - configMapRef:
            name: lms-shared-config
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "384Mi"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
