apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-search-service-blue
  namespace: lms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lms-search-service
      version: blue
  template:
    metadata:
      labels:
        app: lms-search-service
        version: blue
    spec:
      containers:
      - name: lms-search-service
        image: lms-search-service:latest
        ports:
        - containerPort: 8086
        env:
        - name: DEPLOY_COLOR
          value: "blue"
        envFrom:
        - configMapRef:
            name: lms-shared-config
        - secretRef:
            name: lms-secrets
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "384Mi"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8086
          initialDelaySeconds: 40
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8086
          initialDelaySeconds: 40
