spring:
  application:
    name: lms-notification-service
  profiles:
    active: dev
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      enable-auto-commit: true
  redis:
    database: 1
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: 6379
  mail:
    host: smtp.mailtrap.io
    port: 587
    username: ${MAIL_USERNAME:mock}
    password: ${MAIL_PASSWORD:mock}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

springdoc:
  api-docs:
    path: /api/v1/notifications/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://jaeger:4318/v1/traces}

server:
  port: 8088
