management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
      group:
        readiness:
          include: db
      validate-group-membership: false
  health:
    kafka:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://jaeger:4318/v1/traces}

server:
  port: 8081

spring:
  application:
    name: lms-user-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/lms}
    username: ${SPRING_DATASOURCE_USERNAME:lms}
    password: ${SPRING_DATASOURCE_PASSWORD:lms}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
      pool-name: UserServiceHikariPool
  jpa:
    hibernate:
      ddl-auto: validate
    default-schema: lms_user
    show-sql: false
    properties:
      hibernate:
        default_schema: lms_user
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: lms_user
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9093}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

springdoc:
  api-docs:
    path: /api/v1/users/v3/api-docs
