management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://jaeger:4318/v1/traces}

server:
  port: 8081

spring:
  application:
    name: lms-user-service

springdoc:
  api-docs:
    path: /api/v1/users/v3/api-docs
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/lms}
    username: ${SPRING_DATASOURCE_USERNAME:lms}
    password: ${SPRING_DATASOURCE_PASSWORD:lms}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    default-schema: lms_user
    show-sql: false
    properties:
      hibernate:
        default_schema: lms_user
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: lms_user
