apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-analytics-service
  namespace: lms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lms-analytics-service
  template:
    metadata:
      labels:
        app: lms-analytics-service
    spec:
      containers:
      - name: lms-analytics-service
        image: lms-analytics-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8090
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://$(POSTGRES_HOST):$(POSTGRES_PORT)/lms"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: lms-secrets
              key: POSTGRES_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lms-secrets
              key: POSTGRES_PASSWORD
        envFrom:
        - configMapRef:
            name: lms-shared-config
        resources:
          limits:
            cpu: "1000m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8090
          initialDelaySeconds: 180
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8090
          initialDelaySeconds: 180
---
apiVersion: v1
kind: Service
metadata:
  name: lms-analytics-service
  namespace: lms
spec:
  ports:
  - port: 8090
    targetPort: 8090
  selector:
    app: lms-analytics-service
