apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-content-service
  namespace: lms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lms-content-service
  template:
    metadata:
      labels:
        app: lms-content-service
    spec:
      containers:
      - name: lms-content-service
        image: lms-content-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8085
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://$(POSTGRES_HOST):$(POSTGRES_PORT)/lms"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: lms-secrets
              key: POSTGRES_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lms-secrets
              key: POSTGRES_PASSWORD
        - name: LMS_COURSE_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: lms-shared-config
              key: COURSE_SERVICE_URL
        envFrom:
        - configMapRef:
            name: lms-shared-config
        resources:
          limits:
            cpu: "1000m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8085
          initialDelaySeconds: 180
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8085
          initialDelaySeconds: 180
---
apiVersion: v1
kind: Service
metadata:
  name: lms-content-service
  namespace: lms
spec:
  ports:
  - port: 8085
    targetPort: 8085
  selector:
    app: lms-content-service
