apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-search-service
  namespace: lms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lms-search-service
  template:
    metadata:
      labels:
        app: lms-search-service
    spec:
      containers:
      - name: lms-search-service
        image: lms-search-service:latest
        ports:
        - containerPort: 8086
        envFrom:
        - configMapRef:
            name: lms-shared-config
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "384Mi"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8086
          initialDelaySeconds: 40
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8086
          initialDelaySeconds: 40
---
apiVersion: v1
kind: Service
metadata:
  name: lms-search-service
  namespace: lms
spec:
  ports:
  - port: 8086
    targetPort: 8086
  selector:
    app: lms-search-service
