apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-search-service
  namespace: lms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lms-search-service
  template:
    metadata:
      labels:
        app: lms-search-service
    spec:
      containers:
      - name: lms-search-service
        image: lms-search-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8086
        envFrom:
        - configMapRef:
            name: lms-shared-config
        resources:
          limits:
            cpu: "1000m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8086
          initialDelaySeconds: 180
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8086
          initialDelaySeconds: 180
---
apiVersion: v1
kind: Service
metadata:
  name: lms-search-service
  namespace: lms
spec:
  ports:
  - port: 8086
    targetPort: 8086
  selector:
    app: lms-search-service
